#ifndef APPPROPERTIES_H
#define APPPROPERTIES_H

#include <QObject>
#include <QColor>

#include "HMIGlobal.h"
class AppProperties : public QObject
{
    Q_OBJECT
    // OCUBE_READONLY_PROPERTY(int, DEF_DEVICE_WIDTH, 800)
    // OCUBE_READONLY_PROPERTY(int, DEF_DEVICE_HEIGHT, 600)
    OCUBE_READONLY_PROPERTY(int, DEF_DEVICE_POSX, 480)
    OCUBE_READONLY_PROPERTY(int, DEF_DEVICE_POSY, 600)
    OCUBE_READONLY_PROPERTY(int, DEF_BUTTONITEM_HEIGHT, 55)
    OCUBE_READONLY_PROPERTY(int, DEF_IPAD_WIDTH, 960)
    OCUBE_READONLY_PROPERTY(int, DEF_IPAD_HEIGHT, 720)
    //4.3 temp kji
    OCUBE_READONLY_PROPERTY(int, DEF_DEVICE_WIDTH, 480)
    OCUBE_READONLY_PROPERTY(int, DEF_DEVICE_HEIGHT, 272)


    //color define
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_RED, QColor(255, 0, 0))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_BLUE, QColor(0, 0, 255))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_GREEN, QColor(0, 255, 0))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_WHITE, QColor(0xff, 0xff, 0xff))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_GRAY, QColor(130, 130, 130))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_BLACK, QColor(0, 0, 0))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_ORANGE, "orange")
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_PINK, "pink")
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_DEVICENAME, QColor(0x5b, 0x5a, 0x5d))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_TIME, QColor(0x33, 0x33, 0x33))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_USER, QColor(0x33, 0x33, 0x33))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_NOTIFY_NORMAL, QColor(0x31, 0x32, 0x38))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_NOTIFY_WARNING, QColor("#77070B"))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_NOTIFY_ERROR, QColor(0xff, 0x6c, 0x00))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_TOP_DIVIDER, QColor(0xf2, 0xf2, 0xf2))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_BOTTOMINFO_TITLE, QColor(0x77, 0x77, 0x77))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_BOTTOMINFO_CONTENT, QColor(0x33, 0x33, 0x33))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_BOTTOMINFO_TEMPERATURE_COOL, QColor(0x42, 0xa2, 0xe5))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_BOTTOMINFO_TEMPERATURE_DEFROST, QColor(0x48, 0x61, 0x82))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_STATUS_BOTTOMINFO_TEMPERATURE_HEAT, QColor(0xf1, 0x96, 0x3c))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_MENU_BG, QColor(49, 50, 56))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_SUBMENU_BG, QColor(35, 36, 41))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_SUBMENU_TEXTCOLOR_NORMAL, QColor(0xaf, 0xaf, 0xaf))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_SUBMENU_TEXTCOLOR_SELECT, QColor(0xff, 0xff, 0xff))
    OCUBE_READONLY_PROPERTY(QColor, DEF_COLOR_CONTENT_BORDER, QColor("#d2d2d3"))

    //minmax value
    OCUBE_READONLY_MINMAX_PROPERTY(int, DEF_RPM, 0, 9900)
};
#endif // APPPROPERTIES_H
